spring:
  application:
    name: team_yupao
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.119.19.16:3306/team_yupi
    username: root
    password: zzy123456
  session:
    timeout: 86400 # 一天过期

server:
  port: 8080


mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

logging:
  level:
    com.zzy.team: debug
    org.springframework: warn